version: '3.4'

services:
  sigo.assessoriasconsultorias.api:
    image: ${DOCKER_REGISTRY-}sigoassessoriasconsultoriasapi
    build:
      context: .
      dockerfile: src/Modulos/AssessoriasConsultorias/SIGO.AssessoriasConsultorias.API/Dockerfile

  sigo.gestaonormas.api:
    image: ${DOCKER_REGISTRY-}sigogestaonormasapi
    build:
      context: .
      dockerfile: src/Modulos/GestaoNormas/SIGO.GestaoNormas.API/Dockerfile


  sigo.gestaoprocessoindustrial.api:
    image: ${DOCKER_REGISTRY-}sigogestaoprocessoindustrialapi
    build:
      context: .
      dockerfile: src/Modulos/GestaoProcessoIndustrial/SIGO.GestaoProcessoIndustrial.API/Dockerfile


  sigo.apigateway:
    image: ${DOCKER_REGISTRY-}sigoapigateway
    build:
      context: .
      dockerfile: src/APIGateway/SIGO.APIGateway/Dockerfile

