// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGO.AssessoriasConsultorias.Infra.Context;

namespace SIGO.AssessoriasConsultorias.Infra.Migrations
{
    [DbContext(typeof(AssessoriasConsultoriasDbContext))]
    [Migration("20201010002936_MigracaoInicial2")]
    partial class MigracaoInicial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SIGO.AssessoriasConsultorias.Domain.Entities.Contrato", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasMaxLength(200);

                    b.Property<Guid>("GUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasMaxLength(36);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasMaxLength(100);

                    b.Property<int>("ParceiroID")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("ParceiroID");

                    b.ToTable("Contratos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DataCriacao = new DateTime(2020, 10, 9, 21, 29, 36, 247, DateTimeKind.Local).AddTicks(1760),
                            Descricao = "Descrição 1",
                            GUID = new Guid("b00536b6-73ee-4e5c-8773-70b65eb88956"),
                            Nome = "Contrato 1",
                            ParceiroID = 1,
                            URL = "URL"
                        });
                });

            modelBuilder.Entity("SIGO.AssessoriasConsultorias.Domain.Entities.Parceiro", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasMaxLength(200);

                    b.Property<Guid>("GUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasMaxLength(36);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasMaxLength(100);

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint");

                    b.HasKey("ID");

                    b.ToTable("Parceiros");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DataCriacao = new DateTime(2020, 10, 9, 21, 29, 36, 244, DateTimeKind.Local).AddTicks(6226),
                            Descricao = "Descrição 1",
                            GUID = new Guid("93713dc9-63cf-4dee-98ad-610db3c483e8"),
                            Nome = "Contrato 1",
                            Tipo = (short)0
                        });
                });

            modelBuilder.Entity("SIGO.AssessoriasConsultorias.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("SIGO.AssessoriasConsultorias.Domain.Entities.Parceiro", "Parceiro")
                        .WithMany("Contratos")
                        .HasForeignKey("ParceiroID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
