// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGO.GestaoNormas.Infra.Context;

namespace SIGO.GestaoNormas.Infra.Migrations
{
    [DbContext(typeof(GestaoNormasDbContext))]
    [Migration("20201002011159_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SIGO.GestaoNormas.Domain.Entities.Norma", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("GUID")
                        .HasColumnType("char(36)");

                    b.Property<int>("RepositorioID")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("URL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.HasIndex("RepositorioID");

                    b.ToTable("Normas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DataCriacao = new DateTime(2020, 10, 1, 22, 11, 58, 871, DateTimeKind.Local).AddTicks(5876),
                            Descricao = "Norma de Criação de Agentes de Conversação criada por Hitalo de Araujo",
                            GUID = new Guid("7fe6494b-c28a-4fa9-809f-bd63c4bc0aa3"),
                            RepositorioID = 1,
                            Titulo = "Norma de Criação de Agentes de Conversação",
                            URL = "https://github.com/HitaloDeAraujo/AgenteConversacao/blob/master/HITALO%20ARAUJO%20PROJETO%20E%20DESENVOLVIMENTO%20DE%20UM%20ARCABOU%C3%87O%20DE%20AGENTE%20DE%20CONVERSA%C3%87%C3%83O%20-%2011.pdf"
                        });
                });

            modelBuilder.Entity("SIGO.GestaoNormas.Domain.Entities.Repositorio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("GUID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("URL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("Repositorio");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DataCriacao = new DateTime(2020, 10, 1, 22, 11, 58, 867, DateTimeKind.Local).AddTicks(2482),
                            Descricao = "Repositório de Hitalo de Araujo",
                            GUID = new Guid("ed1a358d-a4b8-46f1-8b83-f20170d8e199"),
                            Nome = "Hitalo de Araujo",
                            URL = "https://github.com/HitaloDeAraujo"
                        });
                });

            modelBuilder.Entity("SIGO.GestaoNormas.Domain.Entities.Norma", b =>
                {
                    b.HasOne("SIGO.GestaoNormas.Domain.Entities.Repositorio", "Repositorio")
                        .WithMany("Normas")
                        .HasForeignKey("RepositorioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
