// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGO.GestaoProcessoIndustrial.Infra.Context;

namespace SIGO.GestaoProcessoIndustrial.Infra.Migrations
{
    [DbContext(typeof(GestaoProcessoIndustrialDbContext))]
    [Migration("20201004031814_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SIGO.GestaoProcessoIndustrial.Domain.Entities.Evento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasMaxLength(200);

                    b.Property<string>("GUID")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasMaxLength(36);

                    b.Property<int>("Grau")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasMaxLength(100);

                    b.Property<int>("TipoEventoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TipoEventoID");

                    b.ToTable("Eventos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DataCriacao = new DateTime(2020, 10, 4, 0, 18, 14, 42, DateTimeKind.Local).AddTicks(8574),
                            Descricao = "Desc",
                            GUID = "b2afba3f-fc14-4137-97fc-746ab290fefc",
                            Grau = 1,
                            Nome = "Norma Cadastrada",
                            TipoEventoID = 1
                        });
                });

            modelBuilder.Entity("SIGO.GestaoProcessoIndustrial.Domain.Entities.TipoEvento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("TiposEvento");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DataCriacao = new DateTime(2020, 10, 4, 0, 18, 14, 40, DateTimeKind.Local).AddTicks(3476),
                            Nome = "Norma Cadastrada"
                        },
                        new
                        {
                            ID = 2,
                            DataCriacao = new DateTime(2020, 10, 4, 0, 18, 14, 41, DateTimeKind.Local).AddTicks(6244),
                            Nome = "Norma Atualizada"
                        });
                });

            modelBuilder.Entity("SIGO.GestaoProcessoIndustrial.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasMaxLength(50);

                    b.Property<string>("GUID")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasMaxLength(36);

                    b.Property<string>("Grupos")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DataCriacao = new DateTime(2020, 10, 4, 0, 18, 14, 43, DateTimeKind.Local).AddTicks(731),
                            Email = "123",
                            GUID = "c3f2da62-f5e8-4f2f-bbd5-a8f392688f28",
                            Grupos = "ADMINISTRADOR",
                            Nome = "Hitalo"
                        });
                });

            modelBuilder.Entity("SIGO.GestaoProcessoIndustrial.Domain.Entities.Evento", b =>
                {
                    b.HasOne("SIGO.GestaoProcessoIndustrial.Domain.Entities.TipoEvento", "TipoEvento")
                        .WithMany("Eventos")
                        .HasForeignKey("TipoEventoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
